"""Provider-side Pact verification against the real ReqRes API.

Reads the pact file generated by the consumer tests and verifies that
the real ReqRes API satisfies all defined interactions.
"""

from __future__ import annotations

from pathlib import Path

import pytest
from pact import Verifier  # type: ignore[import]

PACT_FILE = Path(__file__).parents[2] / "pacts" / "MyApp-ReqRes.json"
PROVIDER_BASE_URL = "https://reqres.in"


@pytest.mark.api
class TestUserProviderVerification:
    """Verify the real ReqRes API against our consumer pact contract."""

    def test_provider_satisfies_consumer_pact(self) -> None:
        """Run Pact verifier against the real ReqRes provider."""
        if not PACT_FILE.exists():
            pytest.skip(
                f"Pact file not found at {PACT_FILE}. "
                "Run consumer tests first to generate the pact file."
            )

        verifier = Verifier(
            provider="ReqRes",
            provider_base_url=PROVIDER_BASE_URL,
        )
        output, _ = verifier.verify_pacts(
            str(PACT_FILE),
            verbose=False,
        )
        assert output == 0, (
            f"Pact verification failed. ReqRes does not satisfy consumer contract.\n"
            f"Pact file: {PACT_FILE}"
        )
